[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_WORLDCOIN_CLIENT_ID = "app_cfd0a40d70419e3675be53a0aa9b7e10"
  VITE_BACKEND_URL = "https://magnify-cash-worldid-backend.kevin8396.workers.dev"
  VITE_ENVIRONMENT = "production"
  VITE_MAGNIFY_WORLD_ADDRESS = "0x93dbB2d447F0086aF60B2becc66598fe3D9135A1"

[context.staging.environment]
  VITE_WORLDCOIN_CLIENT_ID = "app_17bda0ba13c1f91c838218d2156b673c"
  VITE_BACKEND_URL = "https://staging-magnify-cash-worldid-backend.kevin8396.workers.dev"
  VITE_ENVIRONMENT = "staging"
  VITE_MAGNIFY_WORLD_ADDRESS = "0xF3b2F1Bdb5f622CB08171707673252C222734Ca3"

[context.development.environment]
  VITE_WORLDCOIN_CLIENT_ID = "app_1801cb2a3556a82b82e2bf667a5f3c8b"
  VITE_BACKEND_URL = "https://dev-magnify-cash-worldid-backend.kevin8396.workers.dev"
  VITE_ENVIRONMENT = "development"
  VITE_MAGNIFY_WORLD_ADDRESS = "0xF3b2F1Bdb5f622CB08171707673252C222734Ca3"
